Remove dbx- function prefix

diff --git a/dbx-get b/dbx-get
--- a/dbx-get
+++ b/dbx-get
@@ -11,18 +11,18 @@ file already exists locally, the case of its name is preserved.
 EOF
 	   )
 
-dbx-parse-options "$@"
+parse-options "$@"
 shift $((OPTIND-1))
 
 P="$1"
-shift && test -n "$P" || dbx-exit-on-missing-args
+shift && test -n "$P" || exit-on-missing-args
 
 shopt -s nocasematch
 
-function dbx-process-match {
+function process-match {
     M=${BASH_REMATCH[0]}
     DBX_FILE="${LINE##$M}"
-    ABS_LOCAL_FILE=`dbx-local-path "$DBX_FILE"`
+    ABS_LOCAL_FILE=`local-path "$DBX_FILE"`
     LOCAL_FILE="${ABS_LOCAL_FILE##$PWD/}"
 }
 
@@ -32,16 +32,16 @@ dbxcli ls -Rl "$DBX_PATH" | \
     while read LINE; do
 	if [[ $LINE =~ ^-[[:blank:]]+-[[:blank:]]+-[[:blank:]]+ ]];
 	then
-	    dbx-process-match
+	    process-match
 	    ACTION="creating local directory $LOCAL_FILE"
 	    mkdir -p "$LOCAL_FILE" && \
 		echo "Success $ACTION" || \
-		    dbx-exit-on-error "Failure $ACTION"
+		    exit-on-error "Failure $ACTION"
 	elif [[ $LINE =~ ^[^/]+ ]]; then
-	    dbx-process-match
+	    process-match
 	    ACTION="downloading $LOCAL_FILE"
 	    dbxcli get "$DBX_FILE" "$LOCAL_FILE" && \
 		echo "Success $ACTION" || \
-		    dbx-exit-on-error "Failure $ACTION"
+		    exit-on-error "Failure $ACTION"
 	fi
     done
diff --git a/dbx-put b/dbx-put
--- a/dbx-put
+++ b/dbx-put
@@ -11,25 +11,25 @@ contents recursively.
 EOF
 	   )
 
-dbx-parse-options "$@"
+parse-options "$@"
 shift $((OPTIND-1))
 
 P="$1"
-shift && test -n "$P" || dbx-exit-on-missing-args
+shift && test -n "$P" || exit-on-missing-args
 
 ABSOLUTE_LOCAL_PATH=`realpath -m "$P"`
 
-dbx-test-in-home "$ABSOLUTE_LOCAL_PATH" ||  \
-    dbx-exit-on-error "Path not in \$DBX_HOME"
+test-in-dbx-home "$ABSOLUTE_LOCAL_PATH" ||  \
+    exit-on-error "Path not in \$DBX_HOME"
 
 DBX_PATH=${ABSOLUTE_LOCAL_PATH##$DBX_HOME/}
 
 cd "$DBX_HOME"
 find "$DBX_PATH" -type f | \
     while read FILE; do
-	ABS_LOCAL_FILE=`dbx-local-path "$FILE"`
+	ABS_LOCAL_FILE=`local-path "$FILE"`
 	LOCAL_FILE="${ABS_LOCAL_FILE##$START_PWD/}"
 	dbxcli put "$FILE" "$FILE" && \
 	    echo "Success uploading $LOCAL_FILE" || \
-		dbx-exit-on-error "Failure uploading $LOCAL_FILE"
+		exit-on-error "Failure uploading $LOCAL_FILE"
     done
diff --git a/dbx-rm b/dbx-rm
--- a/dbx-rm
+++ b/dbx-rm
@@ -10,34 +10,34 @@ contents recursively.
 EOF
 	   )
 
-dbx-parse-options "$@"
+parse-options "$@"
 shift $((OPTIND-1))
 
 REQUESTED_PATH="$1"
-shift || dbx-exit-on-missing-args
+shift || exit-on-missing-args
 
 DBX_PATH=`dbx-path "$REQUESTED_PATH"`
 
-function dbx-is-non-empty-directory {
+function test-is-non-empty-directory {
     dbx-test-dir "$DBX_PATH" 2>/dev/null || return 1
     C=$(dbxcli ls -l "$DBX_PATH" | wc -l)
     test $C -gt 1
 }
 
-if ! dbx-test-option-enabled r; then
-    dbx-is-non-empty-directory && \
-	dbx-exit-on-error "Directory is not empty: $DBX_PATH"
+if ! test-option-enabled r; then
+    test-is-non-empty-directory && \
+	exit-on-error "Directory is not empty: $DBX_PATH"
 fi
 
 # TODO: add y/n query with both paths, absolute
 
-dbx-test-option-enabled r && O=-f || O=
+test-option-enabled r && O=-f || O=
 dbxcli rm $O "$DBX_PATH" || \
-    dbx-exit-on-error "Could not remove from Dropbox: $DBX_PATH"
+    exit-on-error "Could not remove from Dropbox: $DBX_PATH"
 
-LOCAL_PATH=`dbx-local-path "$DBX_PATH"`
+LOCAL_PATH=`local-path "$DBX_PATH"`
 if test -a "$LOCAL_PATH"; then
-    dbx-test-option-enabled r && O=-r || O=
+    test-option-enabled r && O=-r || O=
     rm $O "$LOCAL_PATH" || \
-	dbx-exit-on-error "Could not remove locally: $LOCAL_PATH"
+	exit-on-error "Could not remove locally: $LOCAL_PATH"
 fi
